name: Scheduled Python Script

on: workflow_dispatch
  # schedule:
    # - cron: '0 8 * * *'  # Runs every day at 8:00 AM UTC

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env: 
      PG_URL: ${{ secrets.PG_URL }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have any dependencies, install them here
        pip install requests
        pip install psycopg2
    - name: Run the script
      run: python python-file.py
